import { useEffect, useState } from "react";
import Head from "next/head";
import { getAutomationAlerts, runAutomationScan, resolveAutomationAlert } from "../../lib/api";

export default function AutomationPage(){
  const [alerts,setAlerts]=useState([]), [loading,setLoading]=useState(true), [scanning,setScanning]=useState(false), [error,setError]=useState(""), [status,setStatus]=useState("open");
  const load=async()=>{setLoading(true);setError("");try{const r=await getAutomationAlerts({status});setAlerts(r.alerts||[])}catch(e){setError(e.message||"Unable to load alerts.")}finally{setLoading(false)}};
  useEffect(()=>{load();},[status]);
  const scan=async()=>{setScanning(true);setError("");try{await runAutomationScan();await load()}catch(e){setError(e.message||"Scan failed.")}finally{setScanning(false)}};
  const resolve=async(id)=>{try{await resolveAutomationAlert(id);await load()}catch(e){setError(e.message||"Unable to resolve alert.")}};
  return <><Head><title>AI Automation | Waventra Vetric</title></Head><main style={styles.page}><div style={styles.header}><div><h1>AI Automation</h1><p>Live operational alerts generated from your database.</p></div><div style={styles.actions}><select value={status} onChange={e=>setStatus(e.target.value)} style={styles.select}><option value="open">Open</option><option value="resolved">Resolved</option><option value="all">All</option></select><button onClick={scan} disabled={scanning} style={styles.button}>{scanning?"Scanning…":"Run Scan"}</button></div></div>{error&&<div style={styles.error}>{error}</div>}{loading?<div style={styles.card}>Loading alerts…</div>:alerts.length===0?<div style={styles.card}><h3>No alerts</h3><p>No matching operational signals were found.</p></div>:<div style={styles.grid}>{alerts.map(a=><div key={a._id} style={styles.card}><div style={styles.row}><span style={{...styles.badge,...(a.severity==="critical"?styles.critical:a.severity==="warning"?styles.warning:styles.info)}}>{a.severity.toUpperCase()}</span><span>{new Date(a.detectedAt).toLocaleString()}</span></div><h3>{a.title}</h3><p>{a.message}</p><small>Type: {a.type}</small>{a.status==="open"&&<button onClick={()=>resolve(a._id)} style={styles.resolve}>Mark resolved</button>}</div>)}</div>}<div style={styles.note}>Automation never blocks customers or orders automatically. Alerts are review signals based on live application data.</div></main></>;
}
const styles={page:{minHeight:"100vh",padding:"32px",background:"#071126",color:"#eef4ff",fontFamily:"Inter,Arial,sans-serif"},header:{display:"flex",justifyContent:"space-between",gap:20,alignItems:"center",marginBottom:24},actions:{display:"flex",gap:10},select:{padding:"11px 14px",borderRadius:10,background:"#101d38",color:"white",border:"1px solid #2a3d63"},button:{padding:"11px 16px",border:0,borderRadius:10,background:"#18c8e8",color:"#04101d",fontWeight:800,cursor:"pointer"},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:16},card:{background:"#0d1930",border:"1px solid #20365d",borderRadius:16,padding:20,boxShadow:"0 10px 30px rgba(0,0,0,.18)"},row:{display:"flex",justifyContent:"space-between",gap:12,fontSize:12,color:"#93a7c7"},badge:{padding:"5px 8px",borderRadius:999,fontWeight:800},critical:{background:"#4a1c2a",color:"#ff9cac"},warning:{background:"#463a17",color:"#ffd66b"},info:{background:"#163b4a",color:"#77e4ff"},resolve:{marginTop:14,padding:"9px 12px",borderRadius:8,border:"1px solid #36527e",background:"transparent",color:"#b9c9e4",cursor:"pointer"},error:{background:"#481d2a",color:"#ffb7c3",padding:14,borderRadius:10,marginBottom:16},note:{marginTop:24,color:"#7f94b8",fontSize:13}};
