import {useEffect,useState} from "react";
import ProtectedRoute from "../../components/ProtectedRoute";
import {getRiskAnalysis,getRiskCustomer} from "../../lib/api";

export default function Risk(){return <ProtectedRoute adminOnly><Inner/></ProtectedRoute>}
function Inner(){
 const[d,setD]=useState(null),[loading,setLoading]=useState(true),[err,setErr]=useState(""),[days,setDays]=useState(30),[q,setQ]=useState(""),[customer,setCustomer]=useState(null),[customerLoading,setCustomerLoading]=useState(false);
 const load=()=>{setLoading(true);setErr("");getRiskAnalysis({days}).then(setD).catch(e=>setErr(e.message)).finally(()=>setLoading(false))};
 useEffect(() => { load(); }, [days]);
 const lookup=async()=>{if(!q.trim())return;setCustomerLoading(true);try{setCustomer(await getRiskCustomer(q.trim()))}catch(e){setErr(e.message)}finally{setCustomerLoading(false)}};
 return <main style={S.page}><div style={S.wrap}><div style={S.head}><div><span style={S.badge}>PHASE 18</span><h1>Risk & Anomaly Signals</h1><p>Rule-based signals to help administrators review unusual order patterns. These signals are not fraud determinations.</p></div><div><select value={days} onChange={e=>setDays(e.target.value)} style={S.select}><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option><option value="180">180 days</option></select><button onClick={load} style={S.btn}>{loading?"Checking…":"Refresh"}</button></div></div>
 {err&&<div style={S.err}>{err}</div>}{d&&<><div style={S.stats}><Box t="Orders" v={d.summary.orders}/><Box t="Customers" v={d.summary.uniqueCustomers}/><Box t="Flagged" v={d.summary.flaggedCustomers}/><Box t="High risk" v={d.summary.highRisk}/><Box t="Medium risk" v={d.summary.mediumRisk}/><Box t="High-value orders" v={d.summary.highValueOrders}/></div>
 <section style={S.panel}><h2>Customer signals</h2>{d.signals.length===0?<p>No rule-based signals were triggered in this period.</p>:<div style={S.tableWrap}><table style={S.table}><thead><tr><th>Customer key</th><th>Level</th><th>Score</th><th>Orders</th><th>Cancelled</th><th>Value</th><th>Signals</th></tr></thead><tbody>{d.signals.map(x=><tr key={x.key}><td>{x.key}</td><td><span style={badge(x.level)}>{x.level}</span></td><td>{x.score}</td><td>{x.orderCount}</td><td>{x.cancelledCount}</td><td>₹{Number(x.totalValue).toLocaleString("en-IN")}</td><td>{x.reasons.join(" • ")}</td></tr>)}</tbody></table></div>}</section>
 <section style={S.panel}><h2>Review a customer</h2><div style={S.lookup}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Email, phone or user ID" style={S.input}/><button onClick={lookup} style={S.btn}>{customerLoading?"Checking…":"Check customer"}</button></div>{customer&&<div style={S.customer}><strong>{customer.customer?.name||q}</strong><span>{customer.level} risk · score {customer.score}</span><p>{customer.signals?.length?customer.signals.join(" • "):"No rule-based customer signals."}</p><small>{customer.orders?.length||0} recent matching orders</small></div>}</section>
 <section style={S.note}><b>Methodology:</b> {d.methodology} Thresholds: ₹{d.thresholds.highValueOrder.toLocaleString("en-IN")} high-value order, {d.thresholds.rapidOrderWindowMinutes}-minute rapid-order window.</section></>}</div></main>
}
function Box({t,v}){return <div style={S.box}><small>{t}</small><strong>{v}</strong></div>}
function badge(level){return {display:"inline-block",padding:"4px 9px",borderRadius:99,border:"1px solid #35506a",fontSize:12,fontWeight:800}}
const S={page:{minHeight:"90vh",background:"#07111f",color:"#eef6ff",padding:"38px 18px"},wrap:{maxWidth:1250,margin:"auto"},head:{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",flexWrap:"wrap"},badge:{fontSize:12,letterSpacing:2,color:"#67e8f9"},headH:{},btn:{margin:"10px 0 0 8px",padding:"10px 15px",border:0,borderRadius:10,background:"#22d3ee",fontWeight:800,cursor:"pointer"},select:{padding:"10px",borderRadius:10,background:"#0d1b2d",color:"#eef6ff",border:"1px solid #29425c"},stats:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:12,marginTop:24},box:{background:"#0d1b2d",border:"1px solid #20364e",borderRadius:14,padding:17},boxSmall:{},boxStrong:{},panel:{background:"#0d1b2d",border:"1px solid #20364e",borderRadius:16,padding:20,marginTop:18},tableWrap:{overflowX:"auto"},table:{width:"100%",borderCollapse:"collapse",fontSize:13},lookup:{display:"flex",gap:10,flexWrap:"wrap"},input:{flex:"1 1 300px",padding:11,borderRadius:10,border:"1px solid #29425c",background:"#091726",color:"#eef6ff"},customer:{marginTop:14,padding:15,borderRadius:12,background:"#091726",display:"grid",gap:7},note:{marginTop:18,padding:14,borderRadius:12,border:"1px solid #29425c",color:"#b9c9d8",fontSize:13},err:{marginTop:15,padding:12,borderRadius:10,background:"#3b1117",color:"#fecaca"}}
